server.port=8080
server.ssl.enabled=false

playlistcreator.setlistfm.api-key=${SETLISTFM_API_KEY:}

playlistcreator.spotify.client-id=${SPOTIFY_CLIENT_ID:}
playlistcreator.spotify.client-secret=${SPOTIFY_CLIENT_SECRET:}
playlistcreator.spotify.redirect-uri=${SPOTIFY_REDIRECT_URI:http://127.0.0.1:8080/login/oauth2/code/spotify}

playlistcreator.lastfm.api-key=${LASTFM_API_KEY:}
playlistcreator.lastfm.shared-secret=${LASTFM_SHARED_SECRET:}
