server.port=${PORT:8080}
server.ssl.enabled=false
server.forward-headers-strategy=framework
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

playlistcreator.setlistfm.api-key=${SETLISTFM_API_KEY:}

playlistcreator.spotify.client-id=${SPOTIFY_CLIENT_ID:}
playlistcreator.spotify.client-secret=${SPOTIFY_CLIENT_SECRET:}
playlistcreator.spotify.redirect-uri=${SPOTIFY_REDIRECT_URI:}

playlistcreator.lastfm.api-key=${LASTFM_API_KEY:}
playlistcreator.lastfm.shared-secret=${LASTFM_SHARED_SECRET:}
