package com.application.playlistcreator.service;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import com.application.playlistcreator.client.spotify.SpotifyApiClient;
import com.application.playlistcreator.dto.GeneratePlaylistResponse;
import com.application.playlistcreator.dto.SelectedTrackRequest;
import com.application.playlistcreator.exception.ExternalApiException;
import com.application.playlistcreator.model.SetlistSelection;
import com.application.playlistcreator.model.SpotifyTrackMatch;
import com.application.playlistcreator.model.SpotifyTrackMatch.MatchStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class PlaylistGenerationService {

	private static final Logger log = LoggerFactory.getLogger(PlaylistGenerationService.class);

	private final SetlistService setlistService;
	private final SpotifyTrackMatchingService spotifyTrackMatchingService;
	private final SpotifyApiClient spotifyApiClient;
	private final SongNormalizer songNormalizer;

	public PlaylistGenerationService(SetlistService setlistService,
			SpotifyTrackMatchingService spotifyTrackMatchingService,
			SpotifyApiClient spotifyApiClient,
			SongNormalizer songNormalizer) {
		this.setlistService = setlistService;
		this.spotifyTrackMatchingService = spotifyTrackMatchingService;
		this.spotifyApiClient = spotifyApiClient;
		this.songNormalizer = songNormalizer;
	}

	public GeneratePlaylistResponse generatePlaylist(String accessToken, String artistName, String playlistName,
			String playlistDescription, List<SelectedTrackRequest> selectedTracks) {
		log.info("Starting playlist generation. artistName={}, requestedPlaylistName={}",
				artistName, playlistName);
		SetlistSelection fullSelection = setlistService.selectProbableSongs(artistName);
		Set<String> selectedTitles = selectedTitleKeys(selectedTracks);
		var filteredSongs = fullSelection.recentSongs().stream()
				.filter(song -> selectedTitles.contains(songNormalizer.normalizeTitle(song.title())))
				.toList();
		if (filteredSongs.isEmpty()) {
			throw new ExternalApiException("Select at least one track");
		}
		SetlistSelection selection = new SetlistSelection(
				fullSelection.artist(),
				fullSelection.sourceSetlists(),
				filteredSongs);
		log.info("Setlist selection ready for playlist generation. resolvedArtist={}, setlists={}, recentSongs={}",
				selection.artist().name(), selection.sourceSetlists().size(), selection.recentSongs().size());
		List<SpotifyTrackMatch> matches = spotifyTrackMatchingService.matchTracks(
				accessToken,
				selection.artist().name(),
				selection.recentSongs());
		List<String> matchedUris = matches.stream()
				.filter(match -> match.status() == MatchStatus.MATCHED)
				.map(SpotifyTrackMatch::uri)
				.toList();
		log.info("Spotify matching ready for playlist creation. artistName={}, matchedUris={}",
				selection.artist().name(), matchedUris.size());
		var user = spotifyApiClient.getCurrentUser(accessToken);
		log.info("Spotify current user resolved. userId={}, displayName={}, email={}",
				user.id(), user.display_name(), user.email());
		boolean publicFlag = true;
		String finalPlaylistName = playlistName != null && !playlistName.isBlank()
				? playlistName
				: selection.artist().name() + " - Probabile scaletta";
		String description = playlistDescription != null && !playlistDescription.isBlank()
				? playlistDescription
				: "Playlist generated by playlistcreator";
		var playlist = spotifyApiClient.createPlaylist(accessToken, finalPlaylistName, description, publicFlag);
		log.info("Spotify playlist created. playlistId={}, playlistName={}, requestedPublic={}, returnedPublic={}, url={}",
				playlist.id(), playlist.name(), publicFlag, playlist.publicPlaylist(),
				playlist.external_urls() != null ? playlist.external_urls().get("spotify") : null);
		spotifyApiClient.updatePlaylistVisibility(accessToken, playlist.id(), publicFlag);
		log.info("Spotify playlist visibility enforced. playlistId={}, publicPlaylist={}",
				playlist.id(), publicFlag);
		for (List<String> batch : batches(matchedUris, 100)) {
			log.info("Adding Spotify tracks batch. playlistId={}, batchSize={}", playlist.id(), batch.size());
			spotifyApiClient.addItemsToPlaylist(accessToken, playlist.id(), batch);
		}
		log.info("Playlist generation finished. playlistId={}, addedTracks={}", playlist.id(), matchedUris.size());
		return GeneratePlaylistResponse.from(selection, matches, playlist.id(), playlist.name(),
				playlist.external_urls() != null ? playlist.external_urls().get("spotify") : null,
				matchedUris.size());
	}

	private Set<String> selectedTitleKeys(List<SelectedTrackRequest> selectedTracks) {
		if (selectedTracks == null || selectedTracks.isEmpty()) {
			throw new ExternalApiException("Select at least one track");
		}
		Set<String> keys = new LinkedHashSet<>();
		selectedTracks.stream()
				.filter(track -> track != null && track.title() != null && !track.title().isBlank())
				.map(SelectedTrackRequest::title)
				.map(songNormalizer::normalizeTitle)
				.forEach(keys::add);
		return keys;
	}

	private List<List<String>> batches(List<String> values, int batchSize) {
		List<List<String>> batches = new ArrayList<>();
		for (int start = 0; start < values.size(); start += batchSize) {
			batches.add(values.subList(start, Math.min(start + batchSize, values.size())));
		}
		return batches;
	}
}
