package com.application.playlistcreator.service;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.application.playlistcreator.client.spotify.SpotifyApiClient;
import com.application.playlistcreator.client.spotify.SpotifyApiClient.Track;
import com.application.playlistcreator.dto.SelectedTrackRequest;
import com.application.playlistcreator.exception.ExternalApiException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class TopTracksPlaylistService {

	private static final Logger log = LoggerFactory.getLogger(TopTracksPlaylistService.class);
	private static final int SPOTIFY_PAGE_SIZE = 50;
	private static final Set<Integer> SUPPORTED_TRACK_LIMITS = Set.of(10, 25, 50, 100);
	private static final Map<Integer, String> TIME_RANGES = Map.of(
			1, "short_term",
			6, "medium_term",
			12, "long_term");

	private final SpotifyApiClient spotifyApiClient;

	public TopTracksPlaylistService(SpotifyApiClient spotifyApiClient) {
		this.spotifyApiClient = spotifyApiClient;
	}

	public SelectionResult findTopTracks(String accessToken, Integer requestedLimit, Integer months) {
		int limit = validateTrackLimit(requestedLimit);
		int periodMonths = validateMonths(months);
		String timeRange = TIME_RANGES.get(periodMonths);
		Map<String, Track> uniqueTracks = new LinkedHashMap<>();
		int offset = 0;

		while (uniqueTracks.size() < limit) {
			int pageLimit = Math.min(SPOTIFY_PAGE_SIZE, limit - uniqueTracks.size());
			var page = spotifyApiClient.getCurrentUserTopTracks(accessToken, timeRange, pageLimit, offset);
			List<Track> items = page != null && page.items() != null ? page.items() : List.of();
			for (Track track : items) {
				if (track != null && track.id() != null && track.uri() != null && track.name() != null) {
					uniqueTracks.putIfAbsent(track.id(), track);
				}
			}
			offset += items.size();
			if (items.isEmpty() || items.size() < pageLimit || page.next() == null || page.next().isBlank()) {
				break;
			}
		}

		List<TopTrack> tracks = new ArrayList<>();
		int rank = 1;
		for (Track track : uniqueTracks.values()) {
			if (tracks.size() == limit) {
				break;
			}
			tracks.add(new TopTrack(
					rank++,
					track.id(),
					track.name(),
					track.uri(),
					artistNames(track),
					track.album() != null ? track.album().name() : null));
		}

		String warning = tracks.size() < limit
				? "Spotify returned only " + tracks.size() + " of the " + limit
						+ " requested tracks for this period."
				: null;
		log.info("Spotify top tracks ready. requestedTracks={}, availableTracks={}, months={}, timeRange={}, warning={}",
				limit, tracks.size(), periodMonths, timeRange, warning != null);
		return new SelectionResult(limit, periodMonths, timeRange, List.copyOf(tracks), warning);
	}

	public GenerationResult generatePlaylist(
			String accessToken,
			Integer requestedLimit,
			Integer months,
			List<SelectedTrackRequest> selectedTracks,
			String playlistName,
			String playlistDescription) {
		SelectionResult fullSelection = findTopTracks(accessToken, requestedLimit, months);
		SelectionResult selection = filterSelectedTracks(fullSelection, selectedTracks);
		if (selection.tracks().isEmpty()) {
			throw new ExternalApiException("Spotify did not return any tracks for the selected period");
		}
		String finalName = playlistName != null && !playlistName.isBlank()
				? playlistName.trim()
				: "My Top " + selection.tracks().size() + " - Last " + selection.months() + " Months";
		String description = playlistDescription != null && !playlistDescription.isBlank()
				? playlistDescription.trim()
				: "Playlist generated by playlistcreator from my Spotify top tracks";
		var playlist = spotifyApiClient.createPlaylist(accessToken, finalName, description, true);
		spotifyApiClient.updatePlaylistVisibility(accessToken, playlist.id(), true);
		List<String> uris = selection.tracks().stream().map(TopTrack::uri).toList();
		for (int start = 0; start < uris.size(); start += 100) {
			spotifyApiClient.addItemsToPlaylist(
					accessToken,
					playlist.id(),
					uris.subList(start, Math.min(start + 100, uris.size())));
		}
		log.info("Spotify top tracks playlist generated. playlistId={}, requestedTracks={}, addedTracks={}, months={}",
				playlist.id(), selection.requestedLimit(), uris.size(), selection.months());
		return new GenerationResult(
				selection,
				playlist.id(),
				playlist.name(),
				playlist.external_urls() != null ? playlist.external_urls().get("spotify") : null,
				uris.size());
	}

	private SelectionResult filterSelectedTracks(
			SelectionResult selection,
			List<SelectedTrackRequest> selectedTracks) {
		if (selectedTracks == null || selectedTracks.isEmpty()) {
			throw new ExternalApiException("Select at least one track");
		}
		Set<String> selectedIds = selectedTracks.stream()
				.filter(track -> track != null && track.id() != null && !track.id().isBlank())
				.map(SelectedTrackRequest::id)
				.collect(java.util.stream.Collectors.toSet());
		List<TopTrack> tracks = selection.tracks().stream()
				.filter(track -> selectedIds.contains(track.id()))
				.toList();
		if (tracks.isEmpty()) {
			throw new ExternalApiException("None of the selected tracks is available");
		}
		return new SelectionResult(
				selection.requestedLimit(),
				selection.months(),
				selection.timeRange(),
				tracks,
				selection.warning());
	}

	private int validateTrackLimit(Integer value) {
		int limit = value != null ? value : 25;
		if (!SUPPORTED_TRACK_LIMITS.contains(limit)) {
			throw new ExternalApiException("trackLimit must be one of: 10, 25, 50, 100");
		}
		return limit;
	}

	private int validateMonths(Integer value) {
		int months = value != null ? value : 6;
		if (!TIME_RANGES.containsKey(months)) {
			throw new ExternalApiException("months must be one of: 1, 6, 12");
		}
		return months;
	}

	private List<String> artistNames(Track track) {
		if (track.artists() == null) {
			return List.of();
		}
		return track.artists().stream()
				.filter(artist -> artist != null && artist.name() != null)
				.map(SpotifyApiClient.Artist::name)
				.toList();
	}

	public record TopTrack(
			int rank,
			String id,
			String title,
			String uri,
			List<String> artists,
			String albumName) {
	}

	public record SelectionResult(
			int requestedLimit,
			int months,
			String timeRange,
			List<TopTrack> tracks,
			String warning) {
	}

	public record GenerationResult(
			SelectionResult selection,
			String playlistId,
			String playlistName,
			String playlistUrl,
			int addedTracksCount) {
	}
}
